---
- hosts: all
  become: yes
  tasks:
    - name: create git user
      user:
        name: git
    - name: create git ssh folder
      file:
        path: /home/git/.ssh
        state: directory
        owner: git
        mode: '0700'
    - name: create authorized key file
      copy:
        content: ""
        dest: /home/git/.ssh/authorized_keys
        owner: git
        mode: '0600'

    - name: Create git repos dir
      file:
        path: /srv/git
        state: directory
        owner: git

    - name: Create git repo
      file:
        path: /srv/git/project.git
        state: directory
        owner: git

    - name: Initialize git repository
      command:
        cmd: git init --bare
        chdir: /srv/git/project.git
        creates: /srv/git/project.git/description
      notify: Set git as owner of the repo

  handlers:
    - name: Set git as owner of the repo
      file:
        path: /srv/git/project.git
        owner: git
        recurse: true